In [1]:
import requests
import pandas as pd

In [2]:
teams_response = requests.get('https://data.nba.net/10s/prod/v2/2022/teams.json').json()

In [15]:
teams = teams_response['league']['standard']

In [4]:
teams_df = pd.DataFrame(data=teams).set_index('teamId').drop(['isNBAFranchise', 'isAllStar'], axis=1)

In [5]:
teams_df

,city,altCityName,fullName,tricode,nickname,urlName,teamShortName,confName,divName
teamId,,,,,,,,,
1610612737,Atlanta,Atlanta,Atlanta Hawks,ATL,Hawks,hawks,Atlanta,East,Southeast
1610612738,Boston,Boston,Boston Celtics,BOS,Celtics,celtics,Boston,East,Atlantic
1610612751,Brooklyn,Brooklyn,Brooklyn Nets,BKN,Nets,nets,Brooklyn,East,Atlantic
1610612766,Charlotte,Charlotte,Charlotte Hornets,CHA,Hornets,hornets,Charlotte,East,Southeast
1610612741,Chicago,Chicago,Chicago Bulls,CHI,Bulls,bulls,Chicago,East,Central
1610612739,Cleveland,Cleveland,Cleveland Cavaliers,CLE,Cavaliers,cavaliers,Cleveland,East,Central
1610612742,Dallas,Dallas,Dallas Mavericks,DAL,Mavericks,mavericks,Dallas,West,Southwest
1610612743,Denver,Denver,Denver Nuggets,DEN,Nuggets,nuggets,Denver,West,Northwest
1610612765,Detroit,Detroit,Detroit Pistons,DET,Pistons,pistons,Detroit,East,Central
1610612744,Golden State,Golden State,Golden State Warriors,GSW,Warriors,warriors,Golden State,West,Pacific
1610612745,Houston,Houston,Houston Rockets,HOU,Rockets,rockets,Houston,West,Southwest
1610612754,Indiana,Indiana,Indiana Pacers,IND,Pacers,pacers,Indiana,East,Central
1610612746,LA,LA Clippers,LA Clippers,LAC,Clippers,clippers,LA Clippers,West,Pacific
1610612747,Los Angeles,Los Angeles Lakers,Los Angeles Lakers,LAL,Lakers,lakers,L.A. Lakers,West,Pacific
1610612763,Memphis,Memphis,Memphis Grizzlies,MEM,Grizzlies,grizzlies,Memphis,West,Southwest
1610612748,Miami,Miami,Miami Heat,MIA,Heat,heat,Miami,East,Southeast
1610612749,Milwaukee,Milwaukee,Milwaukee Bucks,MIL,Bucks,bucks,Milwaukee,East,Central
1610612750,Minnesota,Minnesota,Minnesota Timberwolves,MIN,Timberwolves,timberwolves,Minnesota,West,Northwest
1610612740,New Orleans,New Orleans,New Orleans Pelicans,NOP,Pelicans,pelicans,New Orleans,West,Southwest
1610612752,New York,New York,New York Knicks,NYK,Knicks,knicks,New York,East,Atlantic
1610612760,Oklahoma City,Oklahoma City,Oklahoma City Thunder,OKC,Thunder,thunder,Oklahoma City,West,Northwest
1610612753,Orlando,Orlando,Orlando Magic,ORL,Magic,magic,Orlando,East,Southeast
1610612755,Philadelphia,Philadelphia,Philadelphia 76ers,PHI,76ers,sixers,Philadelphia,East,Atlantic
1610612756,Phoenix,Phoenix,Phoenix Suns,PHX,Suns,suns,Phoenix,West,Pacific
1610612757,Portland,Portland,Portland Trail Blazers,POR,Trail Blazers,blazers,Portland,West,Northwest
1610612758,Sacramento,Sacramento,Sacramento Kings,SAC,Kings,kings,Sacramento,West,Pacific
1610612759,San Antonio,San Antonio,San Antonio Spurs,SAS,Spurs,spurs,San Antonio,West,Southwest
1610612761,Toronto,Toronto,Toronto Raptors,TOR,Raptors,raptors,Toronto,East,Atlantic
1610612762,Utah,Utah,Utah Jazz,UTA,Jazz,jazz,Utah,West,Northwest
1610612764,Washington,Washington,Washington Wizards,WAS,Wizards,wizards,Washington,East,Southeast

In [6]:
box_score_response = requests.get('https://data.nba.net/10s/prod/v1/20220616/0042100406_boxscore.json').json()

In [7]:
player_df = pd.DataFrame(box_score_response['stats']['activePlayers']).set_index('personId')
player_df

,firstName,lastName,jersey,teamId,isOnCourt,points,pos,position_full,player_code,min,...,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus,dnp,sortKey
personId,,,,,,,,,,,,,,,,,,,,,
203952,Andrew,Wiggins,22,1610612744,False,18,SF,Small Forward,andrew_wiggins,43:40,...,3,6,5,0,4,3,3,5,,"{'name': 1, 'pos': 0, 'points': 4, 'min': 2, '..."
203490,Otto,Porter Jr.,32,1610612744,False,6,PF,Power Forward,otto_porter_jr,13:02,...,1,1,0,0,0,0,0,3,,"{'name': 2, 'pos': 0, 'points': 12, 'min': 15,..."
203110,Draymond,Green,23,1610612744,True,12,C,Center,draymond_green,41:49,...,8,12,8,1,2,5,2,16,,"{'name': 3, 'pos': 0, 'points': 7, 'min': 3, '..."
202691,Klay,Thompson,11,1610612744,True,12,SG,Shooting Guard,klay_thompson,41:18,...,5,5,2,3,2,3,0,4,,"{'name': 4, 'pos': 0, 'points': 8, 'min': 4, '..."
201939,Stephen,Curry,30,1610612744,True,34,PG,Point Guard,stephen_curry,39:55,...,7,7,7,4,2,2,1,8,,"{'name': 5, 'pos': 0, 'points': 2, 'min': 6, '..."
1626172,Kevon,Looney,5,1610612744,False,0,,,kevon_looney,21:40,...,1,7,1,4,0,1,0,0,,"{'name': 6, 'pos': 0, 'points': 22, 'min': 10,..."
1627780,Gary,Payton II,0,1610612744,False,6,,,gary_payton_ii,19:46,...,2,3,2,5,3,1,1,18,,"{'name': 7, 'pos': 0, 'points': 11, 'min': 11,..."
1629673,Jordan,Poole,3,1610612744,True,15,,,jordan_poole,17:46,...,2,3,2,3,0,0,0,11,,"{'name': 8, 'pos': 0, 'points': 5, 'min': 12, ..."
2738,Andre,Iguodala,9,1610612744,True,0,,,andre_iguodala,1:01,...,0,0,0,0,0,0,0,0,,"{'name': 9, 'pos': 0, 'points': 16, 'min': 21,..."
202357,Nemanja,Bjelica,8,1610612744,False,0,,,nemanja_bjelica,0:00,...,0,0,0,0,0,0,0,0,,"{'name': 10, 'pos': 0, 'points': 26, 'min': 29..."
1630228,Jonathan,Kuminga,00,1610612744,False,0,,,jonathan_kuminga,0:00,...,0,0,0,0,0,0,0,0,,"{'name': 11, 'pos': 0, 'points': 19, 'min': 25..."
1627814,Damion,Lee,1,1610612744,False,0,,,damion_lee,0:00,...,0,0,0,0,0,0,0,0,,"{'name': 12, 'pos': 0, 'points': 17, 'min': 23..."
1630541,Moses,Moody,4,1610612744,False,0,,,moses_moody,0:00,...,0,0,0,0,0,0,0,0,,"{'name': 13, 'pos': 0, 'points': 25, 'min': 28..."
1629308,Juan,Toscano-Anderson,95,1610612744,False,0,,,juan_toscano-anderson,0:00,...,0,0,0,0,0,0,0,0,,"{'name': 14, 'pos': 0, 'points': 20, 'min': 26..."
1628369,Jayson,Tatum,0,1610612738,False,13,SF,Small Forward,jayson_tatum,40:12,...,3,3,7,3,3,5,1,-2,,"{'name': 41, 'pos': 0, 'points': 6, 'min': 5, ..."
201143,Al,Horford,42,1610612738,False,19,PF,Power Forward,al_horford,39:12,...,11,14,2,1,2,3,1,2,,"{'name': 42, 'pos': 0, 'points': 3, 'min': 7, ..."
1629057,Robert,Williams III,44,1610612738,False,10,C,Center,robert_williams,32:37,...,2,7,2,2,0,2,5,-1,,"{'name': 43, 'pos': 0, 'points': 9, 'min': 9, ..."
1627759,Jaylen,Brown,7,1610612738,False,34,SG,Shooting Guard,jaylen_brown,44:00,...,6,7,3,2,1,5,0,1,,"{'name': 44, 'pos': 0, 'points': 1, 'min': 1, ..."
203935,Marcus,Smart,36,1610612738,False,9,PG,Point Guard,marcus_smart,38:29,...,5,6,9,5,2,3,0,7,,"{'name': 45, 'pos': 0, 'points': 10, 'min': 8,..."
1628401,Derrick,White,9,1610612738,False,2,,,derrick_white,16:27,...,1,1,2,1,0,1,0,-26,,"{'name': 46, 'pos': 0, 'points': 14, 'min': 13..."
1630202,Payton,Pritchard,11,1610612738,False,0,,,payton_pritchard,7:57,...,0,1,1,0,0,1,0,-20,,"{'name': 47, 'pos': 0, 'points': 28, 'min': 16..."
1629684,Grant,Williams,12,1610612738,False,3,,,grant_williams,15:51,...,1,1,1,1,0,1,1,-18,,"{'name': 48, 'pos': 0, 'points': 13, 'min': 14..."
203917,Nik,Stauskas,13,1610612738,True,0,,,nik_stauskas,1:03,...,0,0,0,0,0,0,0,-2,,"{'name': 49, 'pos': 0, 'points': 27, 'min': 19..."
1630174,Aaron,Nesmith,26,1610612738,True,0,,,aaron_nesmith,1:03,...,0,0,0,1,0,0,0,-2,,"{'name': 50, 'pos': 0, 'points': 15, 'min': 17..."
1630573,Sam,Hauser,30,1610612738,True,0,,,sam_hauser,1:03,...,0,0,0,0,0,0,0,-2,,"{'name': 51, 'pos': 0, 'points': 29, 'min': 20..."
1628436,Luke,Kornet,40,1610612738,True,0,,,luke_kornet,1:03,...,1,1,0,0,0,1,0,-2,,"{'name': 52, 'pos': 0, 'points': 23, 'min': 18..."
1629752,Juwan,Morgan,4,1610612738,True,0,,,juwan_morgan,1:01,...,0,0,0,0,0,0,0,0,,"{'name': 53, 'pos': 0, 'points': 21, 'min': 22..."
1630238,Malik,Fitts,8,1610612738,False,0,,,malik_fitts,0:00,...,0,0,0,0,0,0,0,0,,"{'name': 54, 'pos': 0, 'points': 24, 'min': 27..."
1628464,Daniel,Theis,27,1610612738,False,0,,,daniel_theis,0:00,...,0,0,0,0,0,0,0,0,,"{'name': 55, 'pos': 0, 'points': 18, 'min': 24..."

In [8]:
def get_box_score(df, player_name):
	player = df[df['player_code'] == player_name]
	return player.get(['points', 'min', 'fgm', 'fga', 'fgp', 'ftm', 'fta', 'ftp', 'tpm', 'tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls', 'steals', 'turnovers', 'blocks', 'plusMinus'])

In [11]:
steph = get_box_score(player_df, 'stephen_curry')
steph

,points,min,fgm,fga,fgp,ftm,fta,ftp,tpm,tpa,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
personId,,,,,,,,,,,,,,,,,,,,
201939,34,39:55,12,21,57.1,4,4,100,6,11,54.5,0,7,7,7,4,2,2,1,8

In [14]:
klay = get_box_score(player_df, 'klay_thompson')
klay

,points,min,fgm,fga,fgp,ftm,fta,ftp,tpm,tpa,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
personId,,,,,,,,,,,,,,,,,,,,
202691,12,41:18,5,20,25.0,0,0,0.0,2,8,25.0,0,5,5,2,3,2,3,0,4

In [19]:
url = 'https://data.nba.net/10s'
response = requests.get(url + "/prod/v1/20220616/0042100406_mini_boxscore.json").json()
response

{'_internal': {'pubDateTime': '2022-06-19 23:35:32.511 EDT',
  'igorPath': 'S3,1655696049698,1655696050331|router,1655696050331,1655696050337|sqlUpdateProcessor,1655696119759,1655696124358|domUpdater,1655696125520,1655696132028|feedProducer,1655696132098,1655696133891',
  'routeName': 'lp_game_video_flag_checker',
  'routeValue': 'S3::ssd_game_video_update.xml',
  'xslt': 'NBA/xsl/game/boxscore/marty_boxscore.xsl',
  'xsltForceRecompile': 'true',
  'xsltInCache': 'false',
  'xsltCompileTimeMillis': '356',
  'xsltTransformTimeMillis': '721',
  'consolidatedDomKey': 'prod__transform__marty_boxscore__2308930759217',
  'endToEndTimeMillis': '84193'},
 'basicGameData': {'seasonStageId': 4,
  'seasonYear': '2021',
  'leagueName': 'standard',
  'gameId': '0042100406',
  'arena': {'name': 'TD Garden',
   'isDomestic': True,
   'city': 'Boston',
   'stateAbbr': 'MA',
   'country': 'USA'},
  'isGameActivated': False,
  'statusNum': 3,
  'extendedStatusNum': 0,
  'startTimeEastern': '9:00 PM ET',
  'startTimeUTC': '2022-06-17T01:00:00.000Z',
  'endTimeUTC': '2022-06-17T03:31:00.000Z',
  'startDateEastern': '20220616',
  'homeStartDate': '20220616',
  'homeStartTime': '2100',
  'visitorStartDate': '20220616',
  'visitorStartTime': '1800',
  'gameUrlCode': '20220616/GSWBOS',
  'clock': '',
  'isBuzzerBeater': False,
  'isPreviewArticleAvail': True,
  'isRecapArticleAvail': True,
  'nugget': {'text': ''},
  'attendance': '0',
  'tickets': {'mobileApp': 'https://a.data.nba.com/tickets/single/2021/0042100406/APP_TIX',
   'desktopWeb': 'https://a.data.nba.com/tickets/single/2021/0042100406/TEAM_SCH',
   'mobileWeb': 'https://a.data.nba.com/tickets/single/2021/0042100406/WEB_MWEB',
   'leagGameInfo': 'https://a.data.nba.com/tickets/single/2021/0042100406/LEAG_GAMEINFO',
   'leagTix': 'https://a.data.nba.com/tickets/single/2021/0042100406/LEAG_TIX'},
  'hasGameBookPdf': False,
  'isStartTimeTBD': False,
  'isNeutralVenue': False,
  'gameDuration': {'hours': '2', 'minutes': '21'},
  'tags': ['Finals2020'],
  'playoffs': {'roundNum': '4',
   'confName': '',
   'seriesId': '40',
   'seriesSummaryText': 'GSW wins 4-2',
   'isSeriesCompleted': True,
   'gameNumInSeries': '6',
   'isIfNecessary': False,
   'vTeam': {'seedNum': '3', 'seriesWin': '4', 'isSeriesWinner': True},
   'hTeam': {'seedNum': '2', 'seriesWin': '2', 'isSeriesWinner': False}},
  'period': {'current': 4,
   'type': 0,
   'maxRegular': 4,
   'isHalftime': False,
   'isEndOfPeriod': False},
  'vTeam': {'teamId': '1610612744',
   'triCode': 'GSW',
   'win': '53',
   'loss': '29',
   'seriesWin': '1',
   'seriesLoss': '1',
   'score': '103',
   'linescore': [{'score': '27'},
    {'score': '27'},
    {'score': '22'},
    {'score': '27'}]},
  'hTeam': {'teamId': '1610612738',
   'triCode': 'BOS',
   'win': '51',
   'loss': '31',
   'seriesWin': '1',
   'seriesLoss': '1',
   'score': '90',
   'linescore': [{'score': '22'},
    {'score': '17'},
    {'score': '27'},
    {'score': '24'}]},
  'watch': {'broadcast': {'broadcasters': {'national': [{'shortName': 'ABC',
       'longName': 'ABC'}],
     'canadian': [{'shortName': 'SN', 'longName': 'Sportsnet'}],
     'vTeam': [],
     'hTeam': [],
     'spanish_hTeam': [],
     'spanish_vTeam': [],
     'spanish_national': []},
    'video': {'regionalBlackoutCodes': '',
     'canPurchase': False,
     'isLeaguePass': True,
     'isNationalBlackout': False,
     'isTNTOT': False,
     'isVR': False,
     'tntotIsOnAir': False,
     'isNextVR': False,
     'isNBAOnTNTVR': False,
     'isMagicLeap': False,
     'isOculusVenues': False,
     'streams': [{'streamType': 'vTeam',
       'isOnAir': False,
       'doesArchiveExist': False,
       'isArchiveAvailToWatch': False,
       'streamId': '',
       'duration': 0},
      {'streamType': 'hTeam',
       'isOnAir': False,
       'doesArchiveExist': False,
       'isArchiveAvailToWatch': False,
       'streamId': '',
       'duration': 0},
      {'streamType': 'espanol_vTeam',
       'isOnAir': False,
       'doesArchiveExist': False,
       'isArchiveAvailToWatch': False,
       'streamId': '',
       'duration': 0},
      {'streamType': 'espanol_hTeam',
       'isOnAir': False,
       'doesArchiveExist': False,
       'isArchiveAvailToWatch': False,
       'streamId': '',
       'duration': 0},
      {'streamType': 'espanol_natl',
       'isOnAir': False,
       'doesArchiveExist': False,
       'isArchiveAvailToWatch': False,
       'streamId': '',
       'duration': 0},
      {'streamType': 'mobile',
       'isOnAir': False,
       'doesArchiveExist': False,
       'isArchiveAvailToWatch': False,
       'streamId': '',
       'duration': 0},
      {'streamType': 'condensed',
       'isOnAir': False,
       'doesArchiveExist': False,
       'isArchiveAvailToWatch': False,
       'streamId': '',
       'duration': 0},
      {'streamType': 'alt',
       'isOnAir': False,
       'doesArchiveExist': False,
       'isArchiveAvailToWatch': False,
       'streamId': '',
       'duration': 0}],
     'deepLink': [{'broadcaster': 'ABC',
       'regionalMarketCodes': '',
       'iosApp': 'http://www.espn.com/watch?id=3957197',
       'androidApp': 'http://www.espn.com/watch?id=3957197',
       'desktopWeb': 'http://www.espn.com/watch?id=3957197',
       'mobileWeb': 'http://www.espn.com/watch?id=3957197'}]},
    'audio': {'national': {'streams': [{'language': 'English',
        'isOnAir': False,
        'streamId': ''},
       {'language': 'Spanish', 'isOnAir': False, 'streamId': ''}],
      'broadcasters': []},
     'vTeam': {'streams': [{'language': 'English',
        'isOnAir': False,
        'streamId': ''},
       {'language': 'Spanish', 'isOnAir': False, 'streamId': ''}],
      'broadcasters': [{'shortName': '95.7 The Game',
        'longName': '95.7 The Game'}]},
     'hTeam': {'streams': [{'language': 'English',
        'isOnAir': False,
        'streamId': ''},
       {'language': 'Spanish', 'isOnAir': False, 'streamId': ''}],
      'broadcasters': [{'shortName': '98.5 The Sports Hub',
        'longName': '98.5 The Sports Hub'}]}}}},
  'officials': {'formatted': [{'firstNameLastName': 'Zach Zarba'},
    {'firstNameLastName': 'David Guthrie'},
    {'firstNameLastName': 'John Goble'}]}}}